name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          debug: true  # Add verbose debugging
          script: |
            whoami  # Verify current user
            pwd     # Check current directory
            cd ~/chat-with-stranger-next
            ls -la  # List files to verify path
            ./.scripts/deploy.sh